import React from "react";
import { GoogleAnalytics } from "@next/third-parties/google";
import { Poppins, Nunito } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["200", "900"],
  subsets: ["latin"], // Specify subsets
});

const nunito = Nunito({
  variable: "--font-nunito",
  weight: ["200", "900"],
  subsets: ["latin"], // Specify subsets
});

export const metadata: Metadata = {
  title: "TalentNovo - talent management platform",
  description: "Generated by create next app",
  openGraph: {
    type: "website",
    url: "https://talentnovo.com",
    title: "TalentNovo - talent management platform",
    description: "Generated by create next app",
    images: [
      {
        url: "https://talentnovo.com/og-image.jpg",
        alt: "TalentNovo",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${nunito.variable}`}>
        {children}
      </body>
      <GoogleAnalytics gaId="G-XX8C2W7P1Z" />
    </html>
  );
}
